Feature/callback
mirumon/mirumon-vk-bot pull request #2
Opened 2019-10-16 16:43 UTC by NoirMorilec

Let me merge in! Leeet me mergeee iiiinnnn

2019-10-16 16:43 UTC, NoirMorilec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить команду просмотра устройств](https://trello.com/c/Mp5SPEY8/38-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2)

2019-10-16 17:01 UTC, Slyfoxy commented on main.py
> +api = vk.API(session, v=5.101)
версию стоит вынести в конфиг. `VK_API_VERSION = 5.101`

2019-10-16 17:10 UTC, nkhitrov approved these changes

2019-10-16 17:10 UTC, Slyfoxy commented on main.py
> +                    f"{computer.name} [{computer.username}]\n"])
неправильная логика. заголовок с доменом должен выводиться один раз и под ним все компьютеры в этом домене. в данном случае заголовок выводится каждый раз

2019-10-16 17:10 UTC, Slyfoxy commented on main.py
> +    raise HTTPException(status_code=400, detail={"error": f"event '{event.type}' not supported"})
статус код не стоит оставлять числом. замени на переменную из пакета [starlette.status](https://fastapi.tiangolo.com/tutorial/response-status-code/)

2019-10-16 17:10 UTC, Slyfoxy commented on message_handler.py
> +    about_computers: str = "/computers"
имхо, но я бы заменил на `computers-list` и вынес в отдельный `Enum` для команд. Все таки этот класс содержит типы сообщений от вк, а не от пользователя

2019-10-16 17:12 UTC, nkhitrov requested changes
Команда `/computers` выводит сообщение не в том формате

2019-10-16 17:47 UTC, NoirMorilec commented on main.py
> +                    f"{computer.name} [{computer.username}]\n"])
Над этим тоже задумывался, но решил сначала так сделать для теста. ща переделаю

2019-10-16 18:03 UTC, Slyfoxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Переписать бота на fastapi](https://trello.com/c/5kVdhpuS/50-%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%B1%D0%BE%D1%82%D0%B0-%D0%BD%D0%B0-fastapi)

2019-10-16 18:13 UTC, NoirMorilec commented on message_handler.py
> +    about_computers: str = "/computers"
Так тут не всё к компьютеру же относится. Тут только одна строчка о них, а все остальное о сообщении приходящем и исходящем соответственно

2019-10-17 17:20 UTC, nsidnev requested changes

2019-10-17 17:20 UTC, nsidnev commented on app/config.py
> +API_VERSION = config("API_VERSION", cast=float, default=5.101)  # noqa: WPS432
5.8 и 5.80 это разные версии, тут не флоат а строка

2019-10-21 21:31 UTC, nkhitrov approved these changes

2019-10-21 21:33 UTC, merged