Feature/programs commit
mirumon/mirumon-vk-bot pull request #3
Opened 2019-11-06 19:21 UTC by NoirMorilec

Added 2 commands: /programs, /computers for bot

2019-11-06 19:21 UTC, NoirMorilec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить команду просмотра установленного ПО на устройстве](https://trello.com/c/AdIsY8ut/84-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B0-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE-%D0%BD%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B5)

2019-11-06 23:29 UTC, Opti213 commented on app/main.py
> +        computer_id = ""
вынеси в отдельный метод, в котором будишь извлекать команду и аргументы

2019-11-06 23:29 UTC, Opti213 commented on app/services/mirumon_api.py
> +import requests
используй httpx. Он умеет в асинхронность

2019-11-06 23:29 UTC, Opti213 commented on app/services/mirumon_api.py
> +    response = requests.get(f"{config.SERVER_URL}/computers")
Когда переделаешь на httpx, зарегай асинхронный клиент и укажи базовый урол, чтоб каждый раз не добавлять ```config.SERVER_URL```

2019-11-06 23:29 UTC, Opti213 commented on app/services/mirumon_api.py
> +    if response.status_code != HTTP_200_OK:
Так же, когда перепишешь на httpx используй is_server_error and is_client_error

2019-11-06 23:29 UTC, Opti213 commented on app/services/send_handler.py
> +    request_path = f"https://api.vk.com/method/docs.save?file={file}&title=programs&tags=programs&v={config.API_VERSION}&access_token={config.TOKEN}"
Вынести

2019-11-06 23:29 UTC, Opti213 commented on app/services/send_handler.py
> +                      attachment=attach)
форматни, чтоб скобки нормально встали

2019-11-10 14:09 UTC, nkhitrov requested changes

2019-11-10 14:09 UTC, nkhitrov commented on app/resources/__init__.py
> +EVENT_ERROR_TEXT = "Ивент не поддерживается"
ивент внутренний термин, пользователь может о нем не знать. лучше заменить на `Данная функция не поддерживается устройством` или что-то подобное

2019-11-10 14:09 UTC, nkhitrov commented on app/resources/__init__.py
> +COMPUTERS_LIST_EMPTY_TEXT = "Нет активных компьютеров"
nit: может лучше включенных/запущенных?

2019-11-10 14:09 UTC, nkhitrov commented on app/resources/__init__.py
> +BASE_VK_URL = "https://api.vk.com"
это в конфиг надо выносить, не в ресурсы

2019-11-10 14:09 UTC, nkhitrov commented on app/services/mirumon_api.py
> +        pass
не нужно переопределять инит, достаточно просто `pass`

2019-11-10 14:09 UTC, nkhitrov commented on app/services/commands_handler.py
> +    func = COMMANDS_HANDLERS[command]  # TODO check null ptr
можно сделать функцию, которая будет отвечать на неправильный ввод команд и заменить конструкцию на `func = COMMANDS_HANDLERS.get(command, no_command_handler)`

2019-11-10 14:09 UTC, nkhitrov commented on app/services/mirumon_api.py
> +        response = client.get(f"/computers/{computer_id}/installed-programs", timeout=15)
а без таймаута разве не работает? он по идее должен дожидаться ответа. и если все таки ставишь таймаут, то выноси его в конфиг

2019-11-10 14:09 UTC, nkhitrov commented on app/services/mirumon_api.py
> +    return [ProgramInfo(**current) for current in response.json()]
nit: `current` стоит заменить на `program`, ибо оно смысловой нагрузки не несет, а по вызову `json()` непонятно, что внутри

2019-11-10 14:09 UTC, nkhitrov commented on app/services/send_handler.py
> +def get_uploaded_file(url):
нет аннотации. начни использовать линтеры из папки `scripts`. если нет интерпретатора баша, скопируй их в `.bat` скрипты (но не удаляй старые!)

2019-11-10 14:09 UTC, nkhitrov commented on app/services/send_handler.py
> +def get_attachable_file(file):
нет аннотации

2019-11-10 14:09 UTC, Slyfoxy commented on app/services/send_handler.py
> +    print(random_id)
принтов быть не должно, нужно заменить на логер `logoru` или хотя бы `logging`. но лучше сразу первый настроить, он лучше

2019-11-10 14:09 UTC, Slyfoxy commented on app/services/utils.py
> +    return worksheet
зачем возвращать объект, если его состояние и так меняется и он передается?
и опять нет аннотаций

2019-11-10 14:09 UTC, Slyfoxy commented on app/services/utils.py
> +        """
закомментированный код

2019-11-10 14:12 UTC, nsidnev commented on app/services/mirumon_api.py
> +        pass
`pass` нельзя, линтер не пропустит

2019-11-10 14:14 UTC, nsidnev requested changes
Необходимо влить коммиты с мастера, чтобы CI проходила

2019-11-10 15:07 UTC, NoirMorilec commented on app/resources/__init__.py
> +COMPUTERS_LIST_EMPTY_TEXT = "Нет активных компьютеров"
Мне кажется, активных тоже норм, но ок, могу поменять

2019-11-10 15:08 UTC, NoirMorilec commented on app/resources/__init__.py
> +BASE_VK_URL = "https://api.vk.com"
Изначально в ресурсы это ты закинул в __init__. Я вот и продолжил эту тенденцию)

2019-11-10 15:10 UTC, NoirMorilec commented on app/services/mirumon_api.py
> +        response = client.get(f"/computers/{computer_id}/installed-programs", timeout=15)
Все время разный разброс таймаута. На компе Макса было 9 с, у меня 7-8 с. Если количество прог будет больше, то таймаут еще больше увеличится. Это и есть тот самый фикс таймаута, о котором я тебе ранее писал. Мы с Максом решили пока оставить так, а когда ты уменьшишь время с 5 до 2-3 с на своей стороне, я тоже подправлю

2019-11-10 15:11 UTC, NoirMorilec commented on app/services/send_handler.py
> +def get_uploaded_file(url):
Вот здесь не понял, лучше поподробнее

2019-11-10 15:11 UTC, NoirMorilec commented on app/services/send_handler.py
> +def get_uploaded_file(url):
Ты имел в виду -> добавить?

2019-11-10 15:12 UTC, NoirMorilec commented on app/services/send_handler.py
> +    print(random_id)
Забыл убрать его, вывод тут вообще не нужен

2019-11-10 15:13 UTC, NoirMorilec commented on app/services/utils.py
> +    return worksheet
Да, здесь чет забылся, сопоставляя функционал как у плюсов

2019-11-10 15:13 UTC, NoirMorilec commented on app/services/utils.py
> +        """
> закомментированный код
уберу

2019-11-10 23:45 UTC, Slyfoxy commented on app/services/send_handler.py
> +def get_uploaded_file(url):
да. и аннотацию для урла

2019-11-10 23:46 UTC, Slyfoxy commented on app/services/mirumon_api.py
> +        pass
ну `noqa` поставить

2019-11-10 23:47 UTC, Slyfoxy commented on app/resources/__init__.py
> +BASE_VK_URL = "https://api.vk.com"
я и не помню уже. странно, не припомню, чтобы этот урл я в ресурсы предлагал кидать. если и было, то мой косяк, да. так не стоит делать

2019-11-14 19:07 UTC, Slyfoxy commented on app/services/mirumon_api.py
> +    if response.status_code != HTTP_200_OK:
будет исправлено в следующем мерже

2019-11-14 19:39 UTC, merged